In [ ]:
#Example 1: 1D, 2D, and 3D arrays
# ---- 1D Array: A simple list of numbers ----

import numpy as np

arr_1d = np.array([10,20,30,40,50])
print("===1D Array===")
print("Array",arr_1d.shape)
print("Dims",arr_1d.ndim)


===1D Array===
Array (5,)
Dims 1


In [19]:
# ---- 2D Array: Rows and Columns (like a spreadsheet) ----
# Think of this as a mini dataset:
#   Row 0 → Student 1 scores [Math, Science, English]
#   Row 1 → Student 2 scores
#   Row 2 → Student 3 scores

arr_2d = np.array([[85, 90, 78],# Student 1
    [92, 88, 95],   # Student 2
    [70, 75, 80]]) # Student 3

print("2D Array 3 subjects x 3 Students")
print(arr_2d)
print("Shape",arr_2d.shape)
print("Dim",arr_2d.ndim)


2D Array 3 subjects x 3 Students
[[85 90 78]
 [92 88 95]
 [70 75 80]]
Shape (3, 3)
Dim 2


In [22]:
# ---- 3D Array: A stack of 2D arrays (like a batch of images) ----
# Imagine 2 grayscale images of size 3×4 pixels

arr_3d = np.array([[[1,  2,  3,  4],   # Image 1, Row 0
     [5,  6,  7,  8],   # Image 1, Row 1
     [9, 10, 11, 12]],  # Image 1, Row 2

    [[13, 14, 15, 16],  # Image 2, Row 0
     [17, 18, 19, 20],  # Image 2, Row 1
     [21, 22, 23, 24]] ]) #Image 2, Row 2

print("\n=== 3D Array (2 images × 3 rows × 4 cols) ===")
print(arr_3d)
print("Shape",arr_3d.shape)
print("Dimension",arr_3d.ndim)



=== 3D Array (2 images × 3 rows × 4 cols) ===
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape (2, 3, 4)
Dimension 3
