 Practice Questions

**Q1.** Create a **1D array** containing odd numbers from 1 to 19 using `np.arange()`.  
Print the array and its shape.

**Q2.** Create a **3×5 matrix** filled with the value `99` using `np.full()`.  
Then create a **4×4 identity matrix** using `np.eye()`.

**Q3.** Create a **3D array** of shape `(2, 4, 3)` filled with zeros.  
Describe what this could represent in an AI/ML context (e.g., "2 batches, 4 rows, 3 columns…").


In [4]:
#Q1.
print("\n 1D array containing odd numbers from 1 to 19")
import numpy as np
range= np.arange(1,20,2)
print(range)


 1D array containing odd numbers from 1 to 19
[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
#Q2.
print("\n 3×5 matrix filled with the value `99` using `np.full()`")

full = np.full((3,5),99)
print(full)

print("===4*4 identify matrix===")
identify = np.eye((4))
print(identify)


 3×5 matrix filled with the value `99` using `np.full()`
[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
===4*4 identify matrix===
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#Q3.
zeros = np.zeros((2,4,3))
print(zeros)





[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
