Practice Q.2: Exploring array attributes

In [2]:
# Create a sample 3D array to inspect
# Imagine: 2 batches of 3 images, each image is 4 pixels wide
import numpy as np
arr = np.array([
    [[1,  2,  3,  4],
     [5,  6,  7,  8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("===Array===")
print(arr)

print("\n Core Attributes")
print(f" . ndim={arr.ndim} → number of dimensions")
print(f" .shape= {arr.shape}→ (batches, rows, cols)")
print(f" .size={arr.size} → total elements (2×3×4 = 24)")
print(f"  .dtype = {arr.dtype} →data type of each element")
print(f".itemsize={arr.itemsize} → bytes per element")
print(f".nbytes    = {arr.nbytes}      → total bytes = size × itemsize")


===Array===
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

 Core Attributes
 . ndim=3 → number of dimensions
 .shape= (2, 3, 4)→ (batches, rows, cols)
 .size=24 → total elements (2×3×4 = 24)
  .dtype = int64 →data type of each element
.itemsize=8 → bytes per element
.nbytes    = 192      → total bytes = size × itemsize


In [3]:
# ---- A float array ----
float_arr = np.array([1.0, 2.5, 3.14], dtype=np.float32)
print("\n=== Float32 array ===")
print(f"  Values    : {float_arr}")
print(f"  dtype     : {float_arr.dtype}")
print(f"  itemsize  : {float_arr.itemsize} bytes  ← half the size of float64!")


=== Float32 array ===
  Values    : [1.   2.5  3.14]
  dtype     : float32
  itemsize  : 4 bytes  ← half the size of float64!
